export const HOME_ROUTE = '/'
export const PROFILE_ROUTE = '/profile'
export const REVIEWS_ROUTE = '/reviews'
export const REVIEW_ROUTE = '/review' + '/:id'
export const MEMBERS_ROUTE = '/members'
export const LOGIN_ROUTE = '/login'
export const SECTOR_ROUTE = '/sectors'
export const SUPORGS_ROUTE = '/suppplyingOrganizations'